---

- name: Install AlternC 3.5 (alternc). Be patient... you can check your social networks!
  apt:
    name: alternc
    cache_valid_time: 3600
    state: latest
  notify: 
  - run alternc.install
## Do we still need to run twice?
## Yes we do: https://github.com/AlternC/AlternC/issues/458
  - run alternc.install 2

###### Workaround, replacing alternc.install. Check for new alternc package releases!
## Up to alternc koumbit version 3.5.0~rc1+0~20201103184407.66~1.gbp1b3d3f, alternc.instal was replaced
## for buster because of a bad check of php version: https://github.com/AlternC/AlternC/issues/459
## Fixed in PR: https://github.com/AlternC/AlternC/pull/461 and packaged in alternc_3.5.0~rc1+0~20210517184411.71~1.gbp3007b6
## Now we have to replace alternc.instal to properly configure opendkim in buster and upper.
## till merge and packaging of PR:  https://github.com/AlternC/AlternC/pull/474
- name: Patch-- replace alternc.install with a fixed version for debian buster
  copy:
    src: files/alternc.install-PR474
    dest: /usr/share/alternc/install/alternc.install
    owner: root
    group: root
    mode: 0755
    backup: yes
  when: alternc_replace_alternc_install | bool

- block: 
  - name: Install "mailman", mailing lists managment system
    apt:
      name: alternc-mailman
      cache_valid_time: 3600
      state: latest
    notify: run alternc.install


  - name: Starting "mailman".
    service: 
      name: mailman 
      state: started
  when: alternc_mailman_install

- block: 
  - name: Install "awstats", websites statistics
    apt:
      name: alternc-awstats
      cache_valid_time: 3600
      state: latest
    notify: run alternc.install

  - name: Checking "{{ alternc_debconf_desktopname }}" domain in "awstats" configuration
    lineinfile:
      path: /etc/awstats/awstats.conf
      regexp: 'SiteDomain='
      line: 'SiteDomain="{{ alternc_debconf_desktopname }}"'
      state: present
      backup: yes

  - name: Building statistics database (awstats).
    shell: "perl /usr/lib/cgi-bin/awstats.pl -config={{ alternc_debconf_desktopname }} -update"
  when: alternc_awstats_install

- name: Install Roundcube, webmail interface
  apt:
    name: alternc-roundcube
    cache_valid_time: 3600
    state: latest
  notify: run alternc.install

- name: Configuring passwords policy. 10 characters mínimum. Upper case letter, lower case letters and numbers are required
  shell: "mysql {{ alternc_query_options }} 'UPDATE policy SET minsize='10', classcount='3''"

### 
## Workaround of this bug
#- name: "workaround: this breaks the file manager panel webpage (still valid??)"
## This one was fixed! --> https://github.com/AlternC/AlternC/issues/402
## (remove these comments somewhere in next versions)
#  copy: 
#    src: files/bro_main.php
#    dest: /usr/share/alternc/panel/admin/bro_main.php
#    owner: alterncpanel
#    group: alterncpanel
#    mode: 0644
#    backup: yes
#  when: ansible_distribution_release == "buster"
#  tags: workaround

#### 
### Workaround of this bug: https://github.com/AlternC/AlternC/issues/404
#- name: Fix opendkim alternc template
#  lineinfile:
#    path: /etc/alternc/templates/opendkim.conf
#    line: PidFile            /run/opendkim/opendkim.pid
#    regexp: ^PidFile
#    backup: yes
#    state: present
#  when: alternc_fix_opendkim_template | bool

- name: Trigger handlers to install AlternC and notify restart Apache2
  meta: flush_handlers
  notify:
  - AlternC - Restart Apache2

...
