---
## file checks_repos.yml of AlternC role
## Check of AlternC requiremnts (acl and quotas)
## set up of alternc and other needed repos

- name: Check if alternc_debconf_alternc_html's partition has ACL and grpquota active
  include_tasks: include/html-mount.yml
  when: mount.mount is defined
  loop: '{{ ansible_facts.mounts }}'
  loop_control:
    loop_var: mount

- name: Set query to check AlternC html mount options
  set_fact:
    alternc_html_mount_query: "[?mount=='{{ alternc_html_mount }}'].options"

- name: ACL of alternc www directory mount
  fail:
    msg: >
        The partition mounted where will be created the html directory for AlternC has no ACL. 
        Such ACL is required by AlternC. Sorry, we stop the installation. Try again building 
        first a host which has ACL activated on the partition where AlternC html files will be
        installed (by default /var/www/alternc).
  when: ansible_facts.mounts | json_query( alternc_html_mount_query ) | first | regex_search('noacl')

- debug: 
    msg: "{{ ansible_facts.mounts | json_query( alternc_html_mount_query ) | first }}"
    verbosity: 2

- name: Group quota on alternc www directory mount
  pause:
    prompt: >
        The partition mounted where will be created the html directory for AlternC (by default 
        /var/www/alternc) has no group quota management. You won't be able to manage AlternC users' quotas. 
        Do you want to continue?
  when: not ansible_facts.mounts | json_query( alternc_html_mount_query ) | first | regex_search('(grpjquota=aquota\.group|grpquota)')


- name: When we want to set a favicon.ico, check if icoutils is installed
  block: 

  - name: Gather the list of local packages
    local_action: package_facts
    become: no
    register: local_packages

  - set_fact:
      # alternc_icoutils: "{{ local_packages | json_query('ansible_facts.packages.icoutils') }}"
      # alternc_icoutils: '{{ local_packages | json_query("ansible_facts.packages[*][?name==`icoutils`]") }}'
      alternc_icoutils: '{{ local_packages | json_query("ansible_facts.packages.icoutils") }}'
      
  - debug: 
      msg: "Ok: alternc_icoutils is defined"
    when: alternc_icoutils is defined
  
  - debug:
      msg: '{{ alternc_icoutils | type_debug }}'

  - name: icoutils package information
    debug: 
      var: alternc_icoutils
      # msg: "{{ local_packages | json_query('ansible_facts.packages.icoutils') | string }}"
      # verbosity: 2

  #- pause: 

  - name: If icoutils not installed
    block: 

    - name: Stop if icoutils is not installed
      pause:
        prompt: Yo want to set a custom favicon.ico and icoutils is not installed on your local controller. Do you want to install it? (Abort if no)

    - name: Ask for "ansible_become_password"
      pause:
        prompt: "Please enter your password for sudo"
        echo: no
      register: ansible_become_pass_input

    - name: Set ansible_become_pass
      set_fact:
        ansible_become_password: '{{ ansible_become_pass_input.user_input }}'

    - name: Install icoutils in local controller
      apt:
        name: icoutils
        state: present
      delegate_to: localhost

#    when: local_packages | json_query("ansible_facts.packages[*].[? name==`icoutils`]") is empty
    when: local_packages | json_query("ansible_facts.packages.icoutils") | type_debug == 'AnsibleUnsafeText'
#    when: local_packages | json_query("ansible_facts.packages.icoutils") == ""

  when: alternc_favicon is string and alternc_favicon != '' 

- debug: 
    msg: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    verbosity: 2

- name: include the variable defining the packages for debian version 
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"

- name: Adding AlternC repository key
  apt_key:
    url: "{{ alternc_repo }}/{{ alternc_key }}"
    state: present

- name: Adding AlternC repository
  apt_repository: 
    repo: "deb {{ alternc_repo }} {{ alternc_branch }}"
    filename: alternc
    state: present
  register: alternc_repo_add

- block: 
  - name: Define stable as preferred debian distribution
    lineinfile: 
      path: /etc/apt/apt.conf.d/30StableRelease
      line: 'APT::Default-Release "stable";'
      create: yes
      state: present

  - name: If distribution is buster, add Sid repository for phpmyadmin
    apt_repository: 
      repo: "deb {{ alternc_debian_sid_repo }} {{ alternc_debian_sid_branch }}"
      state: present
    register: debian_repo_sid_add
  when: ( ansible_distribution == 'Debian') and (ansible_distribution_release == 'buster')
  

- name: Update packages
  apt:
    update_cache: yes
  when: > 
      alternc_repo_add is changed or 
      ( alternc_debian_repo_sid_add is defined and alternc_debian_repo_sid_add is changed )

...