---

- name: Install AlternC 3.5 (alternc). Be patient... you can check your social networks!
  apt:
    name: alternc
    cache_valid_time: 3600
    state: latest
  notify: 
  - run alternc.install
  - run alternc.install 2

- name: Patch-- replace alternc.install with a version for debian buster
  copy:
    src: files/alternc.install
    dest: /usr/share/alternc/install/alternc.install
    owner: root
    group: root
    mode: 0755
    backup: yes
  when: alternc_replace_alternc_install

- block: 
  - name: Install "mailman", mailing lists managment system
    apt:
      name: alternc-mailman
      state: latest
    notify: run alternc.install


  - name: Iniciando "mailman".
    service: 
      name: mailman 
      state: started
  when: alternc_mailman_install

- block: 
  - name: Install "awstats", websites statistics
    apt:
      name: alternc-awstats
      state: latest
    notify: run alternc.install

  - name: Checking "{{ alternc_debconf_desktopname }}" domain in "awstats" configuration
    lineinfile:
      path: /etc/awstats/awstats.conf
      regexp: 'SiteDomain='
      line: 'SiteDomain="{{ alternc_debconf_desktopname }}"'
      state: present
      backup: yes

  - name: Building statistics database (awstats).
    shell: "perl /usr/lib/cgi-bin/awstats.pl -config={{ alternc_debconf_desktopname }} -update"
  when: alternc_awstats_install

- name: Install Roundcube, webmail interface
  apt:
    name: alternc-roundcube
    state: latest
  notify: run alternc.install

- name: Configuring passwords policy. 10 characters mínimum. Upper case letter, lower case letters and numbers are required
  shell: "mysql {{ alternc_query_options }} 'UPDATE policy SET minsize='10', classcount='3''"

# Workaround of this bug
- name: "workaround: this breaks the file manager panel webpage (still valid??)"
  copy: 
    src: files/bro_main.php
    dest: /usr/share/alternc/panel/admin/bro_main.php
    owner: alterncpanel
    group: alterncpanel
    mode: 0644
    backup: yes
  when: ansible_distribution_release == "buster"
  tags: workaround

- name: Trigger handler to restart Apache2
  meta: flush_handlers
  notify:
  - AlternC - Restart Apache2

...
