---
- name: Instalando apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    cache_valid_time: 3600

- name: Instalando augeas-lenses
  apt:
    name: augeas-lenses
    state: present
    cache_valid_time: 3600
  when: ansible_distribution_release == "buster"

- name: Instalando phpmyadmin and php-twig
  apt:
    name: 
    - phpmyadmin
    - php-twig
    - php-symfony-config
    - php-symfony-dependency-injection
    - php-symfony-expression-language
    - php-symfony-service-contracts
    - php-symfony-yaml
    default_release: sid
    state: latest
    cache_valid_time: 3600
  when: ansible_distribution_release == "buster"

- name: Instalando dependencias de alternc-certificate-provider-letsencrypt
  apt:
    name: 
    - python3-cffi-backend
    - python3-distutils
    - python3-lib2to3
    - python3-zope.hookable
    - python3-zope.interface
    default_release: sid
    state: latest
    cache_valid_time: 3600
  when: ansible_distribution_release == "buster"

- name: Instalando AlternC 3.5 (alternc). Tenga paciencia. Espere !!. Mientras puede atender sus redes sociales.
  apt:
    name: alternc
    cache_valid_time: 3600
    state: latest
  notify: 
  - run alternc.install
  - run alternc.install 2

- name: Patch-- replace alternc.install with a version for debian buster
  copy:
    src: files/alternc.install
    dest: /usr/share/alternc/install/alternc.install
    owner: root
    group: root
    mode: 0755
    backup: yes
  when: alternc_replace_alternc_install

- block: 
  - name: Instalando "mailman", sistema de gestión de listas de correo.
    apt:
      name: alternc-mailman
      state: latest
    notify: run alternc.install


  - name: Iniciando "mailman".
    service: 
      name: mailman 
      state: started
  when: alternc_mailman_install

- block: 
  - name: Instalando "awstats", estadísticas para los sitios web.
    apt:
      name: alternc-awstats
      state: latest
    notify: run alternc.install

  - name: Verificando dominio "{{ alternc_debconf_desktopname }}" en configuración de "awstats".
    lineinfile:
      path: /etc/awstats/awstats.conf
      regexp: 'SiteDomain='
      line: 'SiteDomain="{{ alternc_debconf_desktopname }}"'
      state: present
      backup: yes

  - name: Construyendo base de datos para estadísticas (awstats).
    shell: "perl /usr/lib/cgi-bin/awstats.pl -config={{ alternc_debconf_desktopname }} -update"
  when: alternc_awstats_install

- name: Instalar roundcube
  apt:
    name: alternc-roundcube
    state: latest
  notify: run alternc.install

- name: Configurando política de contraseñas. 10 caracteres mínimo. Mayúsculas, minúsculas y números son obligatorios.
  shell: "mysql {{ alternc_query_options }} 'UPDATE policy SET minsize='10', classcount='3''"

## has side effects, better to run alternc.install twice https://github.com/AlternC/AlternC/issues/403
#- name: hook-- Alternc debian installer set wrong file ownership 
#  file:
#    path: /etc/alternc/my.cnf
#    group: alterncpanel
#    state: file

#- name: Ejecutando alternc.install
#  shell: "alternc.install"
#  register: alternc_install_result

# Workaround of this bug
- name: "workaround: this breaks the file manager panel webpage"
  copy: 
    src: files/bro_main.php
    dest: /usr/share/alternc/panel/admin/bro_main.php
    owner: alterncpanel
    group: alterncpanel
    mode: 0644
    backup: yes
  when: ansible_distribution_release == "buster"
  tags: workaround

- name: running alternc.install
  meta: flush_handlers
  notify:
  - AlternC - Restart Apache2

...
