---
# tasks file for ansible-AlternC
#########################################################################
## First playbook: https://git.interior.edu.uy/oscarf/alternc35_ansible
### Oscar Ford: oscarf@ei.udelar.edu.uy - Espacio Interdisciplinario, Udelar.
### Convert to role: Cristhian Choque - CCI - UdelaR
### Publish role: Daniel Viñar - CCI - UdelaR (ulvida
###############################################

- name: Verificando sistema operativo y versión.
  assert:
    that:
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version'] | int >= 9
    msg: "Ejecución abortada. El sistema operativo debe ser Debian(9) Stretch o superior."

- debug: 
    var: ansible_facts

- include_tasks: packages.yml

- include_tasks: install-mysql.yml

- include_tasks: debconf.yml

- import_tasks: install-alternc.yml

- import_tasks: configure-alternc.yml

- include_tasks: post-install.yml

- import_tasks: extra-tasks.yml

- import_tasks: alternc-slavedns.yml
  # tags: alternc_slavedns

...
