---
# tasks file for ansible-AlternC
#########################################################################
## First playbook: https://git.interior.edu.uy/oscarf/alternc35_ansible
### Oscar Ford: oscarf@ei.udelar.edu.uy - Espacio Interdisciplinario, Udelar.
### Convert to role: Cristhian Choque - CCI - UdelaR
### Publish role: Daniel Viñar - CCI - UdelaR (ulvida
###############################################

- name: Verificando sistema operativo y versión.
  assert:
    that:
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version'] | int >= 9
    msg: "Ejecución abortada. El sistema operativo debe ser Debian(9) Stretch o superior."

- debug: 
    var: ansible_facts
    verbosity: 3

- include_tasks: 10_checks-repos.yml

- include_tasks: 20_debconf.yml

- include_tasks: 30_packages.yml

- import_tasks: 40_install-alternc.yml

- import_tasks: 50_configure-alternc.yml

- include_tasks: 60_post-install.yml

- import_tasks: 70_extra-tasks.yml

- import_tasks: 80_alternc-slavedns.yml

- import_tasks: 90_alternc-custom.yml

...
