---
# tasks file for ansible-AlternC
#########################################################################
## First playbook: https://git.interior.edu.uy/oscarf/alternc35_ansible
### Oscar Ford: oscarf@ei.udelar.edu.uy - Espacio Interdisciplinario, Udelar.
### Convert to role: Cristhian Choque - CCI - UdelaR
### Publish role: Daniel Viñar - CCI - UdelaR (ulvida
###############################################

- name: Verificando sistema operativo y versión.
  assert:
    that:
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version'] | int >= 9
    msg: "Ejecución abortada. El sistema operativo debe ser Debian(9) Stretch o superior."

- debug: 
    var: ansible_facts
    verbosity: 3

- include_tasks: 10_checks-repos.yml

- include_tasks: 20_debconf.yml

- include_tasks: 30_packages.yml

- import_tasks: 40_install-alternc.yml

- import_tasks: 50_configure-alternc.yml

- include_tasks: 60_post-install.yml

- name: Login into just installed AlternC panel with admin user
  uri:
    url: '{{ alternc_desktop_protocol }}://{{ alternc_debconf_desktopname }}/login.php'
    method: POST
    follow_redirects: all
    body_format: form-urlencoded
    body: 
      username: admin
      password: '{{ alternc_admin_pass }}'
  register: alternc_panel_login
  become: no
  delegate_to: localhost
  ignore_errors: yes

- name: Optional stop if invalid certificates
  pause:
    prompt: >
      LetsEncrypt certificate of AlternC panel were not (yet?) generated. It may happend after, but on
      some plateforms (such as a Proxmox LXC container with buster) SSL certificate auto-provision is broken.
  when:
  - alternc_panel_login is failed
  - alternc_panel_login.msg | regex_search( 'CERTIFICATE_VERIFY_FAILED')  

- name: Login into just installed AlternC panel with admin user, accepting invalid certs
  uri:
    url: '{{ alternc_desktop_protocol }}://{{ alternc_debconf_desktopname }}/login.php'
    method: POST
    follow_redirects: all
    validate_certs: no
    body_format: form-urlencoded
    body: 
      username: admin
      password: '{{ alternc_admin_pass }}'
    return_content: yes
  register: alternc_panel_login_invalid_certs
  become: no
  delegate_to: localhost
  when: alternc_panel_login is failed

- debug:
    var: alternc_panel_login_invalid_certs

- import_tasks: 70_extra-tasks.yml

- import_tasks: 80_alternc-slavedns.yml
  tags: alternc_slave_dns

- import_tasks: 90_alternc-custom.yml
  tags: alternc_custom

- name: Logout form AlternC panel when succeed with valid certs
  uri:
    url: '{{ alternc_desktop_protocol }}://{{ alternc_debconf_desktopname }}/mem_logout.php'
    method: GET
    follow_redirects: all
    headers:
      Cookie: "{{ alternc_panel_login.set_cookie }}"
  register: alternc_panel_logout
  become: no
  delegate_to: localhost
  when: alternc_panel_login is succeeded

- name: Logout form AlternC panel when succeed with invalid certs
  uri:
    url: '{{ alternc_desktop_protocol }}://{{ alternc_debconf_desktopname }}/mem_logout.php'
    method: GET
    follow_redirects: all
    validate_certs: no
    headers:
      Cookie: "{{ alternc_panel_login_invalid_certs.set_cookie }}"
  register: alternc_panel_logout_invalid_certs
  when: 
  - alternc_panel_login_invalid_certs is not skipped
  - alternc_panel_login_invalid_certs is succeeded

...
