---
# Repos and packages for AltenC installation

- name: Check if alternc_debconf_alternc_html's partition has ACL and grpquota active
  include_tasks: include/html-mount.yml
  when: mount.mount is defined
  loop: '{{ ansible_facts.mounts }}'
  loop_control:
    loop_var: mount

- name: Set query to check AlternC html mount options
  set_fact:
    alternc_html_mount_query: "[?mount=='{{ alternc_html_mount }}'].options"

- name: ACL of alternc www directory mount
  fail:
    msg: >
        The partition mounted where will be created the html directory for AlternC has no ACL. 
        Such ACL is required by AlternC. Sorry, we stop the installation. Try again building 
        first a host which has ACL activated on the partition where AlternC html files will be
        installed (by default /var/www/alternc).
  when: ansible_facts.mounts | json_query( alternc_html_mount_query ) | first | regex_search('noacl')

- debug: 
    msg: "{{ ansible_facts.mounts | json_query( alternc_html_mount_query ) | first }}"
    verbosity: 2

- name: Group quota on alternc www directory mount
  pause:
    prompt: >
        The partition mounted where will be created the html directory for AlternC (by default 
        /var/www/alternc) has no group quota management. You won't be able to manage AlternC users' quotas. 
        Do you want to continue?
  when: not ansible_facts.mounts | json_query( alternc_html_mount_query ) | first | regex_search('(grpjquota=aquota\.group|grpquota)')

#  acl:
#    path: "{{ alternc_html_mount }}"
#  register: alternc_www_acl

- debug: 
    msg: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    verbosity: 2

- name: include the variable defining the packages for debian version 
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"

- name: Agregando repositorio para AlternC
  template:
    src: etc/apt/sources.list.d/alternc.list.j2
    dest: /etc/apt/sources.list.d/alternc.list

- name: Agregar llave apt de repositorio AlternC
  apt_key:
    url: "{{ alternc_repo }}/{{ alternc_key }}"
    state: present

- block: 
  - name: definir la estable como distribuci贸n preferida
    lineinfile: 
      path: /etc/apt/apt.conf.d/30StableRelease
      line: 'APT::Default-Release "stable";'
      create: yes
      state: present

  - name: agregar el repositorio de Sid para phpmyadmin, en debian Buster
    apt_repository: 
      repo: "deb {{ url_repo_sid }} {{ url_branch_sid }}"
      state: present
  when: ( ansible_distribution == 'Debian') and (ansible_distribution_release == 'buster')

- name: Actualizando lista de paquetes.
  apt:
    update_cache: yes

- name: Asegurando que los m贸dulos php mas populares se encuentran actualizados e instalados # M贸dulos de prop贸sito general pero que no se incluye en el instalador de AlternC
  apt:
    name: "{{ alternc_packages }}"
    state: latest

...
